### ISSUE TITLE
memory exhaustion crash

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/sexpr-wasm-prototype#98]
This file crashes the prototype. [crash_sexpre_proto.wast.txt](https://github.com/WebAssembly/sexpr-wasm-prototype/files/454160/crash_sexpre_proto.wast.txt)

It crashes with
```
crash_sexpre_proto.wast:3569:37: memory exhausted
                  (else (if (i32.eq (get_local $jump_dest) (i32.const 16940))
```

The file is over 50,000 line. I'm generating it with [evm2wasm](https://github.com/ewasm/evm2wasm/) and I added optimization to shink the size. But the source program is huge to start with and I don't  think I can make it much smaller on my end.

**Comment by binji** [comment]
Looks like this doesn't have anything to do with file size, only with Bison recursion depth. It's caused by using a right-recursive grammar. Originally I tried to rewrite the grammar in the spec repo to be left-recursive, but it was often creating other issues.

Anyway, it looks like the simplest solution is to increase `YYMAXDEPTH`; the default is 10000 with a scary sounding quote:

>   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

So I printed `YYSTACK_BYTES(YYMAXDEPTH)`: 980142 bytes. OK, I think we can increase that. :-)
